
var obj2= {                                         //monalisa
	{
	"language":"English",
		"key": "IitbJszd1kM",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/450px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	//"context":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	//"context":"Le titre de la peinture, qui est connu en anglais comme Mona Lisa, provient d'une description par l'historien de l'art de la Renaissance Giorgio Vasari, qui a écrit «Leonardo a entrepris de peindre, pour Francesco del Giocondo, le portrait de Mona Lisa, sa femme. Mona en italien est une forme polie d'adresse originale comme ma donna - semblable à Madame, Madame, ou ma dame en anglais. Cela devint madone, et sa contraction mona. Le titre de la peinture, bien que traditionnellement orthographié "Mona", est également couramment épelé dans l'italien moderne comme Monna Lisa mais ceci est rare en anglais."
"context":"The Mona Lisa  is a half-length portrait of Lisa Gherardini by the Italian Renaissance artist Leonardo da Vinci, which has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world.
The painting is a portrait of Lisa Gherardini, the wife of Francesco del Giocondo, and is in oil on a white Lombardy poplar panel, and is believed to have been painted between 1503 and 1506. Leonardo may have continued working on it as late as 1517. It was acquired by King Francis I of France and is now the property of the French Republic, on permanent display at the Louvre Museum in Paris since 1797."

	}
	{
	"language":"French",
		"key": "IitbJszd1kM",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/450px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	//"context":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	"context":"Le titre de la peinture, qui est connu en anglais comme Mona Lisa, provient d'une description par l'historien de l'art de la Renaissance Giorgio Vasari, qui a écrit «Leonardo a entrepris de peindre, pour Francesco del Giocondo, le portrait de Mona Lisa, sa femme. Mona en italien est une forme polie d'adresse originale comme ma donna - semblable à Madame, Madame, ou ma dame en anglais. Cela devint madone, et sa contraction mona. Le titre de la peinture, bien que traditionnellement orthographié "Mona", est également couramment épelé dans l'italien moderne comme Monna Lisa mais ceci est rare en anglais."


	}

	
	{
	"language":"German",
		"key": "IitbJszd1kM",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/450px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
	//	"context": "The Thinker (French: Le Penseur) is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work shows a nude male figure of over life-size sitting on a rock with his chin resting on one hand as though deep in thought and is often used as an image to represent philosophy. There are about 28 full size castings, in which the figure is about 186 centimetres (73 in) high, though not all were made during Rodin's lifetime and under his supervision; as well as various other versions, several in plaster, studies, and posthumous castings, in a range of sizes. Rodin first conceived the figure as part of another work in 1880, but the first of the familiar monumental bronze castings did not appear until 1904.Originally named The Poet (French: Le Poète), The Thinker was initially a figure in a large commission, begun in 1880, for a doorway surround called The Gates of Hell. Rodin based this on The Divine Comedy of Dante, and most of the many figures in the work represented the main characters in the epic poem. Some critics believe The Thinker, at the centre of the composition over the doorway and at about 70 cm high larger than most other figures, was originally intended to depict Dante at the gates of Hell, pondering his great poem. However, there are questionable aspects to this interpretation, including that the figure is naked, while Dante is fully clothed throughout his poem, and that the figure, as used, in no way corresponds to Dante's effete figure. The sculpture is nude, as Rodin wanted a heroic figure in the tradition of Michelangelo, to represent intellect as well as poetry."
	//"context":"Le Penseur est une sculpture en bronze d'Auguste Rodin, généralement placée sur un socle en pierre. Le travail montre une figure nue masculine de taille normale assise sur un rocher avec son menton reposant d'une main comme si profondément dans la pensée et est souvent utilisé comme image pour représenter la philosophie. Il ya environ 28 pièces coulées, dont le chiffre est d'environ 186 centimètres (73 po) de haut, mais pas tous ont été faites pendant la vie Rodin et sous sa supervision, Ainsi que diverses autres versions, plusieurs dans le plâtre, les études et les pièces moulées posthumes, dans une gamme de tailles. Rodin a d'abord conçu la figure dans le cadre d'une autre œuvre en 1880, mais le premier des pièces moulées en bronze monumental ne paraît pas avant 1904."
	//"context":"Le titre de la peinture, qui est connu en anglais comme Mona Lisa, provient d'une description par l'historien de l'art de la Renaissance Giorgio Vasari, qui a écrit «Leonardo a entrepris de peindre, pour Francesco del Giocondo, le portrait de Mona Lisa, sa femme. Mona en italien est une forme polie d'adresse originale comme ma donna - semblable à Madame, Madame, ou ma dame en anglais. Cela devint madone, et sa contraction mona. Le titre de la peinture, bien que traditionnellement orthographié "Mona", est également couramment épelé dans l'italien moderne comme Monna Lisa mais ceci est rare en anglais."
//"context":"The Mona Lisa  is a half-length portrait of Lisa Gherardini by the Italian Renaissance artist Leonardo da Vinci, which has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world.
//The painting is a portrait of Lisa Gherardini, the wife of Francesco del Giocondo, and is in oil on a white Lombardy poplar panel, and is believed to have been painted between 1503 and 1506. Leonardo may have continued working on it as late as 1517. It was acquired by King Francis I of France and is now the property of the French Republic, on permanent display at the Louvre Museum in Paris since 1797."
"context":"Die Mona Lisa ist ein halbes Porträt von Lisa Gherardini von dem italienischen Renaissance-Künstler Leonardo da Vinci, der als "die bekanntesten, am meisten besuchten, die am meisten gesprochenen, die am meisten gesungenen, die meisten parodierten Arbeit von Kunst in der Welt .
Das Gemälde ist ein Porträt von Lisa Gherardini, die Frau von Francesco del Giocondo, und ist in Öl auf einem weißen Lombardei-Pappel-Panel und wird vermutlich zwischen 1503 und 1506 gemalt worden sein. Leonardo kann weiter daran gearbeitet haben, so spät wie 1517 Es wurde von König Franz I. von Frankreich erworben und ist jetzt Eigentum der Französischen Republik, auf Dauerausstellung im Louvre Museum in Paris seit 1797.

	}


{
	"language":"Hindi",
		"key": "IitbJszd1kM",
		"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/450px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
	//, die Frau von Francesco del Giocondo, und ist in Öl auf einem weißen Lombardei-Pappel-Panel und wird vermutlich zwischen 1503 und 1506 gemalt worden sein. Leonardo kann weiter daran gearbeitet haben, so spät wie 1517 Es wurde von König Franz I. von Frankreich erworben und ist jetzt Eigentum der Französischen Republik, auf Dauerausstellung im Louvre Museum in Paris seit 1797.
"context":"मोना लिसा इतालवी पुनर्जागरण कलाकार लियोनार्डो द विंसी द्वारा लिसा गोहरादीनी का आधा-लम्बाई का चित्र है, जिसे "सबसे प्रसिद्ध, सबसे ज्यादा जाने वाला, सबसे ज्यादा लिखा गया, सबसे ज्यादा गाया जाता है, सबसे अधिक विडंबना वाला काम दुनिया में कला 
यह पेंटिंग फ्रांसेस्को डेल जियोकोंडो की पत्नी लिसा गोहरादीनी का एक चित्र है, और वह सफेद लोम्बार्डी पॉपल पैनल पर तेल में है और माना जाता है कि वह 1503 और 1506 के बीच चित्रित किया गया था। लियोनार्डो ने 1517 के रूप में देर तक काम करना जारी रखा हो सकता है यह फ्रांस के राजा फ्रांसिस प्रथम द्वारा अधिग्रहण किया गया था और अब फ्रांसीसी गणराज्य की संपत्ति है, 17 9 17 के बाद से पेरिस के लौवर संग्रहालय में स्थायी प्रदर्शन पर।"

	}
};



use appdb;
db.Monalisa1.find().pretty();